# Generated by Django 4.2.6 on 2023-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_choice_choice_text_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
